### ISSUE TITLE
pre-commit fails, cannot find node

### ISSUE THREAD

**Issue by onedr0p** [onedr0p/k3s-gitops-arm#11]
```bash
pre-commit run --all-files
[INFO] Initializing environment for git://github.com/pre-commit/pre-commit-hooks.
[INFO] Initializing environment for https://github.com/jorisroovers/gitlint.
[INFO] Initializing environment for https://github.com/openstack/bashate.
[INFO] Initializing environment for https://github.com/mattlqx/pre-commit-sign.
[INFO] Initializing environment for https://github.com/Lucas-C/pre-commit-hooks.
[INFO] Initializing environment for https://github.com/jumanjihouse/pre-commit-hooks.
[INFO] Initializing environment for https://github.com/ansible/ansible-lint.git.
[INFO] Initializing environment for https://github.com/igorshubovych/markdownlint-cli.
[INFO] Installing environment for git://github.com/pre-commit/pre-commit-hooks.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/openstack/bashate.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/Lucas-C/pre-commit-hooks.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/ansible/ansible-lint.git.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/igorshubovych/markdownlint-cli.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
An unexpected error has occurred: CalledProcessError: Command: ('/usr/local/Cellar/pre-commit/1.20.0/libexec/bin/python3.7', '-mnodeenv', '--prebuilt', '--clean-src', '/Users/devin/.cache/pre-commit/repotmwccurm/node_env-system', '-n', 'system')
Return code: 1
Expected return code: 0
Output: (none)
Errors:
    Traceback (most recent call last):
      File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
        "__main__", mod_spec)
      File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
        exec(code, run_globals)
      File "/usr/local/Cellar/pre-commit/1.20.0/libexec/lib/python3.7/site-packages/nodeenv.py", line 1480, in <module>
        main()
      File "/usr/local/Cellar/pre-commit/1.20.0/libexec/lib/python3.7/site-packages/nodeenv.py", line 1076, in main
        create_environment(env_dir, opt)
      File "/usr/local/Cellar/pre-commit/1.20.0/libexec/lib/python3.7/site-packages/nodeenv.py", line 913, in create_environment
        install_activate(env_dir, opt)
      File "/usr/local/Cellar/pre-commit/1.20.0/libexec/lib/python3.7/site-packages/nodeenv.py", line 845, in install_activate
        assert shim_node, "Did not find nodejs or node system executable"
    AssertionError: Did not find nodejs or node system executable

Check the log at /Users/devin/.cache/pre-commit/pre-commit.log
```

Node is here :weirdface:

```bash
❯ node --version
v13.2.0
```

**Comment by onedr0p** [comment]
I ran `pre-commit run --all-files` again and it works /shrug
